name: chaperone
description: "Chaperone: Stories By You."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.7
  google_sign_in: ^6.2.1
  firebase_vertexai: ^1.0.4
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.0
  shared_preferences: ^2.3.4
  toastification: ^2.3.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  amplify_flutter: ^2.5.0
  font_awesome_flutter: ^10.8.0
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  email_validator: ^3.0.0
  audioplayers: ^6.1.0
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
# To launch run: dart run flutter_native_splash:create
  flutter_native_splash: ^2.4.3
# To launch run: dart run flutter_launcher_icons
  flutter_launcher_icons: ^0.14.2
flutter_launcher_icons:
  image_path: "assets/images/logo_only_4x_black_bg_1152.jpeg"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/logo_only_4x_black_bg_1152.jpeg"
  android: true
  ios: true
  min_sdk_android: 21
  web:
   generate: true
   image_path: "assets/images/logo_only_4x.png"
flutter_native_splash:
  color: "#212121"
  image: "assets/images/logo_4x.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
